stages:
  - prod

prod:
  stage: prod
  script:
    - echo "$SSH_KEY_INOVAESTUDIOS" > key.pem
    - chmod 600 key.pem
    - ssh -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" -i key.pem root@inovaestudios.com.br "cd /dados/webapps  && pm2 list"
  only:
    - main
